### ISSUE TITLE
Settings for timestamp property names

### ISSUE THREAD

**Issue by notuntoward** [lighthousedino/obsidian-front-matter-timestamps#1]
This would be really nice, but unfortunately, I've already got hundreds of notes using the property names  `created date` and `modified date` which seems to be a default from somewhere.

Would it be possible to make the timestamp property names a setting?

**Comment by pookhaosc1** [comment]
[Added](https://github.com/lighthousedino/obsidian-front-matter-timestamps/releases/tag/1.2.0)! You can also update it from within Obsidian. Let me know if it works.
