### ISSUE TITLE
Feature request: Setting for excludeing folders

### ISSUE THREAD

**Issue by walle89** [lighthousedino/obsidian-front-matter-timestamps#4]
It would be nice if there was a setting to exclude a folder and all its subfolders with notes that this plugin shouldn't touch. For example, templates for the Template plugin.

**Comment by pookhaosc1** [comment]
[Added](https://github.com/lighthousedino/obsidian-front-matter-timestamps/releases/tag/1.3.0)!

**Comment by walle89** [comment]
Thank you! Seems to be working as expected. 🎉
